version: '3.8'

services:
  nginx:
    image: nginx
    volumes:
      - ./docker/zaakbrug-nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - zaakbrug
      - zaakbrug-backend
    ports:
      - 9000:9000
    depends_on:
      - zaakbrug

  zaakbrug:
    build: .
    image: dogbytes/openforms2bpel:latest
    container_name: zaakbrug
    volumes: &zaakbrug-database-data
      - ../frank-runner/data:/usr/local/tomcat/data
      # - ./data:/usr/local/tomcat/data
    networks:
      - zaakbrug
      - zaakbrug-backend
    ports:
      - 8080:8080

volumes:
  database-data:
  media:
  private-media:

networks:
  zaakbrug:
    name: zaakbrug-stack
  zaakbrug-backend:
