version: '3.8'

services:
  nginx:
    image: nginx
    volumes:
      - ./docker/zaakbrug-nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - zaakbrug-stack
      - zaakbrug-backend
    ports:
      - 9000:9000
    depends_on:
      - openforms2bpel

  openforms2bpel:
    build:
      context: .
      args:
        FF_VERSION: ${FF_VERSION:-9.0.0-20241129.042326}
    image: wearefrank/openforms2bpel:${OPENFORMS2BPEL_VERSION:-latest}
    environment:
      zaakbrug.zds.timezone: UTC
      TZ: Europe/Amsterdam
    volumes:
      - ../frank-runner/data:/usr/local/tomcat/data
      - logs:/usr/local/tomcat/logs
      - ./src/main/configurations:/opt/frank/configurations:ro
      - ./src/main/resources:/opt/frank/resources
      - ./src/test/testtool:/opt/frank/testtool
    networks:
      - zaakbrug-stack
      - zaakbrug-backend
    ports:
      - 8080:8080

volumes:
  logs:
  media:
  private-media:

networks:
  zaakbrug-stack:
  zaakbrug-backend:
