version: '3.8'

services:
  nginx:
    image: nginx
    volumes:
      - ./docker/zaakbrug-nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - zaakbrug-stack
      - zaakbrug-backend
    ports:
      - 9000:9000
    depends_on:
      - openforms2bpel

  openforms2bpel:
    build:
      context: .
      args:
        FF_VERSION: ${FF_VERSION:-8.1.0-RC2-20240411.160355}
    image: wearefrank/openforms2bpel:${OPENFORMS2BPEL_VERSION:-latest}
    environment:
      - openforms2bpel.workflows.formdata-collector-stylesheet-file=FormDataCollector_ObjectsApi_Custom.xslt
      - openforms2bpel.workflows.formdata-transform-stylesheet-file=FormDataTransform_Custom.xslt
    volumes:
      - ../frank-runner/data:/usr/local/tomcat/data
      - logs:/usr/local/tomcat/logs
      - ./src/main/configurations:/opt/frank/configurations:ro
      - ./src/test/testtool:/opt/frank/testtool
      - ./docker/openforms2bpel/transforms/FormDataCollector_ObjectsApi_Custom.xslt:/opt/frank/resources/FormDataCollector_ObjectsApi_Custom.xslt
      - ./docker/openforms2bpel/transforms/FormDataTransform_Custom.xslt:/opt/frank/resources/FormDataTransform_Custom.xslt
    networks:
      - zaakbrug-stack
      - zaakbrug-backend
    ports:
      - 8080:8080

volumes:
  logs:
  media:
  private-media:

networks:
  zaakbrug-stack:
  zaakbrug-backend:
