version: '3.8'

x-openforms2bpel-postgres-env:
  environment: &openforms2bpel-postgres-env
    POSTGRES_USER: openforms2bpel
    POSTGRES_PASSWORD: openforms2bpel
    POSTGRES_DB: openforms2bpel

services:
  openforms2bpel-postgres:
    image: postgres:${POSTGRES_VERSION:-14}
    environment: 
      <<: *openforms2bpel-postgres-env
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5400:5432
    networks:
      - zaakbrug-backend
    volumes:
      - openforms2bpel-postgres-data:/var/lib/postgresql/data
  
  openforms2bpel-pgadmin:
    profiles:
      - pgadmin
    image: dpage/pgadmin4:${PGADMIN_VERSION:-latest}
    user: root
    command: ["/venv/bin/python3", "/pgadmin4/setup.py", "--load-servers", "openforms2bpel-pgadmin-conf.json", "--user", "admin@wearefrank.nl"]
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@wearefrank.nl
      PGADMIN_DEFAULT_PASSWORD: admin
    networks:
      - zaakbrug-stack
      - zaakbrug-backend
    depends_on:
      - openforms2bpel-postgres

  openforms2bpel:
    environment: 
      <<: *openforms2bpel-postgres-env
      DB_HOSTNAME: openforms2bpel-postgres
      DB_PORT: 5432
    volumes:
      - ./docker/openforms2bpel-postgres/context.xml:/usr/local/tomcat/conf/Catalina/localhost/ROOT.xml:rw
    depends_on:
      - openforms2bpel-postgres

volumes:
  openforms2bpel-postgres-data:
