version: '3.8'

services:
  nginx:
    image: nginx
    volumes:
      - ./docker/zaakbrug-nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - zaakbrug-stack
      - zaakbrug-backend
    ports:
      - 9000:9000
    depends_on:
      - zaakbrug

  zaakbrug:
    build: .
    image: wearefrank/zaakbrug:latest
    container_name: zaakbrug.dev
    environment:
      - zaakbrug.zds.timezone=UTC
      - TZ=Europe/Amsterdam
    volumes: &zaakbrug-database-data
      - ../frank-runner/data:/usr/local/tomcat/data
      - logs:/usr/local/tomcat/logs
      # - ./data:/usr/local/tomcat/data
      - ./src/main/configurations:/opt/frank/configurations:ro
    networks:
      - zaakbrug-stack
      - zaakbrug-backend
    ports:
      - 8080:8080

volumes:
  logs:
  database-data:
  media:
  private-media:

networks:
  zaakbrug-stack:
  zaakbrug-backend:
