version: '3.8'

services:
  frank-mailslurper:  
    image: oryd/mailslurper:smtps-latest
    volumes:
      - ./docker/mailslurper/config.json:/go/src/github.com/mailslurper/mailslurper/cmd/mailslurper/config.json
    ports:
      - 8025:8025
      - 8026:8080
    networks:
      - zaakbrug-stack
      - zaakbrug-backend

  openforms2bpel:
    environment:
      openforms2bpel.connections.noReplySmtp.enabled: true
      openforms2bpel.connections.noReplySmtp.host: frank-mailslurper
      openforms2bpel.connections.noReplySmtp.port: 2500
      openforms2bpel.connections.noReplySmtp.useSsl: false
      openforms2bpel.connections.noReplySmtp.timeout: 60000
      openforms2bpel.connections.noReplySmtp.authAlias: noreply-smtp
    depends_on:
      - frank-mailslurper
