version: '3.8'

services:
  frank-mailslurper:  
    image: oryd/mailslurper:smtps-latest
    volumes:
      - ./docker/mailslurper/config.json:/go/src/github.com/mailslurper/mailslurper/cmd/mailslurper/config.json
    ports:
      - 8025:8025
    networks:
      - zaakbrug-stack
      - zaakbrug-backend

  openforms2bpel:
    environment:
      openforms2bpel.noreply-smtp.host: frank-mailslurper
      openforms2bpel.noreply-smtp.port: 2500
      openforms2bpel.noreply-smtp.use-ssl: false
      openforms2bpel.noreply-smtp.timeout: 60000
      openforms2bpel.noreply-smtp.auth-alias: noreply-smtp
    depends_on:
      - frank-mailslurper
